print('Hello! please give me all your information ...')
first_name = input('What is your first name? ')
last_name = input('and last name? ')
gage = input('how old are you? ')
gaddress = input('your mommas home address: ')
gphone = input('Phone number aswell: ')
gemail = input('Give me your Email, so i can send you phishing scams please: ')
print('thank you ..')
if int(gage) != int(100):
    new_age = 100 - int(gage)
    current_year = int(2019)
    when_100 = int(new_age) + int(current_year)
    print(('You will be 100 years old in ' + str(when_100)+'\n') * int(gage))
